export const widgetStyles = {
  container: {
    position: 'fixed',
    bottom: '20px',
    right: '20px',
    zIndex: 9999,
  },
  launcherButton: {
    width: '60px',
    height: '60px',
    borderRadius: '50%',
    backgroundColor: '#0070f3',
    color: 'white',
    border: 'none',
    fontSize: '28px',
    cursor: 'pointer',
    boxShadow: '0 4px 14px 0 rgba(0, 118, 255, 0.39)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  panel: {
    width: '350px',
    height: '500px',
    boxShadow: '0 5px 40px rgba(0,0,0,0.15)',
    borderRadius: '10px',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'white',
  },
  header: {
    padding: '10px',
    backgroundColor: '#f9f9f9',
    borderBottom: '1px solid #eee',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    margin: 0,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
  },
  headerButton: {
    background: 'none',
    border: 'none',
    fontSize: '20px',
    cursor: 'pointer',
    color: '#888',
    width: '30px',
    textAlign: 'center',
  },
  chatList: {
    flex: 1,
    overflowY: 'auto',
  },
  chatListItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '15px',
    cursor: 'pointer',
    borderBottom: '1px solid #f0f0f0',
    width: '100%',
    textAlign: 'left',
    border: 'none',
    backgroundColor: 'transparent',
    transition: 'background-color 0.2s ease',
    fontFamily: 'inherit',
    fontSize: 'inherit',
  },
  chatListIcon: {
    fontSize: '24px',
    marginRight: '12px',
    width: '30px',
    textAlign: 'center',
  },
  chatListName: {
    fontWeight: 600,
  },
  chatContainer: {
    flex: 1,
    position: 'relative',
  },
  panelContent: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
    textAlign: 'center',
  },
} as const;
